services:
  postgres:
    image: postgres:13
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mlflow:
    build: .
    container_name: mlflow_server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - mlflow:/app
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
    user: 0:0
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow_db
      --host 0.0.0.0
      --port 5000

volumes:
  pg_data:
  mlflow:
